### ISSUE TITLE
Clean up master :-(

### ISSUE THREAD

**Issue by thefangbear** [Roobotics-FRC/RooBotPost2017#8]
My mistake while `rebase`ing somehow merged training into master with no conflicts. Now training and master are synchronized, we need to clean master branch up 😢

**Comment by jrr6** [comment]
WE EXPLICITLY DECIDED **NOT** TO MERGE TRAINING INTO MASTER!

**Comment by thefangbear** [comment]
Sorry, my mistake :(

**Comment by thefangbear** [comment]
Apparently `git pull` while having a merge request open on GitHub has some unintended side effects.

**Comment by jrr6** [comment]
Can we roll back master to its state prior to your merge?

**Comment by jrr6** [comment]
If you don't object, I'm going to force-push a reversion back to the state of `master` before your merges today. `training` is in no shape to be merged into `master`.

**Comment by jrr6** [comment]
The mangled master branch has been moved to `broken-master`. If you want to clean that up, fine; don't assign it to me. I've reset our real `master` to its state prior to the modifications made today.

**Comment by thefangbear** [comment]
OK, thanks. Apologies for the mistake.
